---
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 6"
  push:

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/${{ github.repository }}:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
